public class EkartProb {
    private String id,name;
    private int qty;
    float price,rating;
    static int count = 0;

    {
        count++;
    }
    //Autogenerated id
    EkartProb(String name,int qty, float price, float rating){
        this.id="A"+count;
        this.name=name;
        this.price=price;
        this.qty=qty;
        this.price=price;
        this.rating=rating;
    }
    //Custom
    public EkartProb(String id,String name,int qty, float price, float rating){
        this.id=id;
        this.name=name;
        this.price=price;
        this.qty=qty;
        this.price=price;
        this.rating=rating;
    }
    public EkartProb(String name,float price, float rating ){
        this.id="A"+count;
        this.name=name;
        this.price=price;
        this.qty=200;
        this.price=price;
        this.rating=rating;
    }
    //@Override
    public String toString(){
        return "EkartProb[id=" + id + ", name=" + name + ", qty=" + qty + ", price=" + price + ", rating=" + rating + "]";
    }
    public static void main(String[] args){
        EkartProb p1 = new EkartProb("mouse", 25, 345.2f, 4.5f);
        EkartProb p2 = new EkartProb("CD", 50, 1234.45f, 3.7f);
        EkartProb p3 = new EkartProb("X123", "charger", 12, 1000.2f, 5f);
        
    }
}
